=== oscarnovillo/Lenguajes-de-Marcas-DAW/HTMLXML/public_html/xml/newXmlSchema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="persons"> 
        <xs:complexType>
            <xs:sequence>
                <xs:element name="person" maxOccurs="unbounded">
                    <xs:complexType>
                        
                        <xs:sequence>
                            <xs:element name="firstname" type="xs:string"/>
                            <xs:element name="lastname" type="xs:string"/>
                            <xs:element name="children" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="childname" type="xs:string"
                                                    maxOccurs="unbounded"/>
                                        
                                    </xs:sequence>
                                    <xs:attribute name="lang" type="xs:string" fixed="EN"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="lang" type="xs:string" default="EN"/>
                    </xs:complexType>
                </xs:element>
            
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== oscarnovillo/Lenguajes-de-Marcas-DAW/HTMLXML/public_html/xml/newXMLDocument2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<persons
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='newXmlSchema.xsd'>
    <person lang="EN">
        <firstname></firstname>
        <lastname></lastname>
        <children lang="EN">
            <childname></childname>
            <childname></childname>
            <childname></childname>
        </children>
    </person>
    <person lang="EN">
        <firstname></firstname>
        <lastname></lastname>
        <children lang="EN">
            <childname></childname>
        </children>
    </person>
    <person lang="EN">
        <firstname></firstname>
        <lastname></lastname>
        <children lang="EN">
            <childname></childname>
        </children>
    </person>

</persons>

=== oscarnovillo/Lenguajes-de-Marcas-DAW/HTMLXML/public_html/xml/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>

<persons 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="newXmlSchema.xsd"
>

<person lang="PP">
  <firstname>Hege</firstname>
  <lastname>Refsnes</lastname>
  <children>
    <childname>Cecilie</childname>
  </children>
</person>

<person>
  <firstname>Stale</firstname>
  <lastname>Refsnes</lastname>
</person>

</persons>

=== oscarnovillo/Lenguajes-de-Marcas-DAW/HTMLXML/public_html/xml/personas3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<persons
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='newXmlSchema.xsd'>
    <person lang="EN">
        <firstname>hola</firstname>
        <lastname></lastname>
        <children lang="EN">
            <childname></childname>
        </children>
        <children lang="EN">
            <childname></childname>
        </children>
        <children lang="EN">
            <childname></childname>
        </children>
    </person>
    <person lang="EN">
        <firstname>1</firstname>
        <lastname></lastname>
        <children lang="EN">
            <childname></childname>
        </children>
        <children lang="EN">
            <childname></childname>
        </children>
        <children lang="EN">
            <childname></childname>
        </children>
    </person>
    <person lang="EN">
        <firstname>1233</firstname>
        <lastname></lastname>
        <children lang="EN">
            <childname></childname>
        </children>
        <children lang="EN">
            <childname></childname>
        </children>
        <children lang="EN">
            <childname></childname>
        </children>
    </person>

</persons>
