=== oscarnovillo/Lenguajes-de-Marcas-DAW/HTMLXML/public_html/xml/newXMLDocument1.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/newXMLDocument1.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE arg SYSTEM "newXMLDocument1.dtd">

    <arg>
    ...
    </arg>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT arg (tipo|jijo)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tipo (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT jijo (al|KI)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT KI (#PCDATA)>
<!ELEMENT al (#PCDATA)>
<!ATTLIST al
    s CDATA #IMPLIED
  >

=== oscarnovillo/Lenguajes-de-Marcas-DAW/HTMLXML/public_html/xml/newXMLDocument1.xml
<?xml version="1.0" encoding="UTF-8"?>

 <!DOCTYPE arg SYSTEM "newXMLDocument1.dtd">

<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<arg>
    <tipo>titulo</tipo>
    <jijo>
        
        <al s="2">hola</al>
        <KI>51</KI>
        <al s="1 45">adios</al>
        <KI>2</KI>
         <KI>56</KI>
    </jijo>
    
</arg>
